name: Simple React
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  echo-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run echo command
        run: echo "Hello from GitHub Actions!"