name: Simple React
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  echo-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Echo GitHub Context Variables
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Git Reference: ${{ github.ref }}"
          echo "Branch: $(echo ${{ github.ref }} | sed 's|refs/heads/||')"